apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 8081
      targetPort: http-grafana
      nodePort: 31700
      protocol: TCP
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
