apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 80
      targetPort: http-grafana
      protocol: TCP
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
