#test1
name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./terraform
        output-file: ../README.md
        output-method: inject
        git-push: "true"
        
    - name: Add README.md to staging
      run: git add ../README.md

    - name: Commit README.md
      run: git commit -m "Update README.md with terraform docs" || echo "No changes to commit"

    - name: Push changes
      run: git push origin ${{ github.head_ref }}

