name: Update README

on:
  push:
    branches:
      - main
#  workflow_dispatch:
#  schedule:
#    # Runs at 5:00 UTC every Monday
#    - cron: '* * * * *'


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform Docs
        uses: docker://quay.io/terraform-docs/terraform-docs:latest

      - name: Update README
        run: |
          terraform-docs markdown table terraform/ --output-file README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update README.md with terraform-docs"
          git push
